name: Dispatch CLI Version Update

on:
  workflow_call:
    inputs:
      cli_version:
        description: 'CLI version to update (no input will take latest)'
        required: false
        default: ''
        type: string

jobs:
  update_java_wrapper:
    name: Update Java Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set Up Environment
        uses: ./.github/actions/setup
        with:
          python-version: '3.x'

      - name: Trigger Update Event On Java Wrapper Repo
        env:
          GH_ORG: 'CheckmarxDev'
          GH_REPO: 'ast-cli-java-wrapper'
          CLI_VERSION: ''
          GITHUB_TOKEN: ${{ secrets.DISPATCH_GH_TOKEN }}
        run: python ./.github/scripts/dispatch_event.py

  update_github_action:
    name: Update Github Action
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set Up Environment
        uses: ./.github/actions/setup
        with:
          python-version: '3.x'

      - name: Trigger Update Event On Github Action Repo
        env:
          GH_ORG: 'Checkmarx'
          GH_REPO: 'ast-github-action'
          CLI_VERSION: ${{ inputs.cli_version }}
          GITHUB_TOKEN: ${{ secrets.DISPATCH_GH_TOKEN }}
        run: python ./.github/scripts/dispatch_event.py

  update_javescript_wrapper_action:
    name: Update Javascript Wrapper Action
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set Up Environment
        uses: ./.github/actions/setup
        with:
          python-version: '3.x'

      - name: Trigger Update Event On Javascript Wrapper Repo
        env:
          GH_ORG: 'CheckmarxDev'
          GH_REPO: 'ast-cli-javascript-wrapper'
          CLI_VERSION: ${{ inputs.cli_version }}
          GITHUB_TOKEN: ${{ secrets.DISPATCH_GH_TOKEN }}
        run: python ./.github/scripts/dispatch_event.py

