name: Dispatch CLI Version Update

on:
  workflow_call:
    inputs:
      is_cli_release:
        type: boolean
        default: true
        description: 'Workflow will update all repos that directly consume the CLI'
      is_js_release:
        type: boolean
        default: false
        description: 'Workflow will update all repos that directly consume the JavaScript Wrapper'
      is_js_runtime_release:
        type: boolean
        default: false
        description: 'Workflow will update all repos that directly consume the JavaScript Runtime Wrapper'
      is_java_release:
        type: boolean
        default: false
        description: 'Workflow will update all repos that directly consume the Java Wrapper'
      cli_version:
        description: 'CLI version to update (no input will take latest)'
        required: false
        default: ''
        type: string

jobs:
  # Group CLI-related updates
  update_cli_consumers:
    name: Update CLI Consumers
    runs-on: ubuntu-latest
    if: ${{ inputs.is_cli_release == true }}
    strategy:
      matrix:
        repo: [
          { org: 'CheckmarxDev', name: 'ast-cli-java-wrapper' },
          { org: 'Checkmarx', name: 'ast-github-action' },
          { org: 'CheckmarxDev', name: 'ast-cli-javascript-wrapper' },
          { org: 'CheckmarxDev', name: 'ast-cli-javascript-wrapper-runtime-cli' },
          { org: 'Checkmarx', name: 'ast-teamcity-plugin' },
          { org: 'Checkmarx', name: 'ast-visual-studio-extension' }
        ]
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Check Out External Repository
        uses: actions/checkout@v3
        with:
          repository: Checkmarx/plugins-release-workflow
          path: plugins-release-workflow

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Trigger Update Event on ${{ matrix.repo.name }}
        env:
          GH_ORG: ${{ matrix.repo.org }}
          GH_REPO: ${{ matrix.repo.name }}
          CLI_VERSION: ${{ inputs.cli_version }}
          IS_CLI_RELEASE: 'true'
          GITHUB_TOKEN: ${{ secrets.DISPATCH_GH_TOKEN }}
        run: python plugins-release-workflow/.github/scripts/dispatch_new_version_event.py

  # Group JavaScript Wrapper-related updates
  update_js_wrapper_consumers:
    name: Update JavaScript Wrapper Consumers
    runs-on: ubuntu-latest
    if: ${{ inputs.is_js_release == true }}
    strategy:
      matrix:
        repo: [
          { org: 'Checkmarx', name: 'ast-vscode-extension' }
        ]
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Check Out External Repository
        uses: actions/checkout@v3
        with:
          repository: Checkmarx/plugins-release-workflow
          path: plugins-release-workflow

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Trigger Update Event on ${{ matrix.repo.name }}
        env:
          GH_ORG: ${{ matrix.repo.org }}
          GH_REPO: ${{ matrix.repo.name }}
          CLI_VERSION: ${{ inputs.cli_version }}
          IS_JS_RELEASE: 'true'
          GITHUB_TOKEN: ${{ secrets.DISPATCH_GH_TOKEN }}
        run: python plugins-release-workflow/.github/scripts/dispatch_new_version_event.py

  # Group JavaScript Runtime Wrapper-related updates
  update_js_runtime_wrapper_consumers:
    name: Update JavaScript Runtime Wrapper Consumers
    runs-on: ubuntu-latest
    if: ${{ inputs.is_js_runtime_release == true }}
    strategy:
      matrix:
        repo: [
          { org: 'Checkmarx', name: 'ast-azure-plugin' }
        ]
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Check Out External Repository
        uses: actions/checkout@v3
        with:
          repository: Checkmarx/plugins-release-workflow
          path: plugins-release-workflow

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Trigger Update Event on ${{ matrix.repo.name }}
        env:
          GH_ORG: ${{ matrix.repo.org }}
          GH_REPO: ${{ matrix.repo.name }}
          CLI_VERSION: ${{ inputs.cli_version }}
          IS_JS_RUNTIME_RELEASE: 'true'
          GITHUB_TOKEN: ${{ secrets.DISPATCH_GH_TOKEN }}
        run: python plugins-release-workflow/.github/scripts/dispatch_new_version_event.py

  # Group Java Wrapper-related updates
  update_java_wrapper_consumers:
    name: Update Java Wrapper Consumers
    runs-on: ubuntu-latest
    if: ${{ inputs.is_java_release == true }}
    strategy:
      matrix:
        repo: [
          { org: 'Checkmarx', name: 'ast-jetbrains-plugin' },
          { org: 'Checkmarx', name: 'ast-eclipse-plugin' },
          { org: 'jenkinsci', name: 'checkmarx-ast-scanner-plugin' }
        ]
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Check Out External Repository
        uses: actions/checkout@v3
        with:
          repository: Checkmarx/plugins-release-workflow
          path: plugins-release-workflow

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Trigger Update Event on ${{ matrix.repo.name }}
        env:
          GH_ORG: ${{ matrix.repo.org }}
          GH_REPO: ${{ matrix.repo.name }}
          CLI_VERSION: ${{ inputs.cli_version }}
          IS_JAVA_RELEASE: 'true'
          GITHUB_TOKEN: ${{ secrets.DISPATCH_GH_TOKEN }}
        run: python plugins-release-workflow/.github/scripts/dispatch_new_version_event.py
