name: Issue automation

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  notify_jira:
    name: Notify Jira
    uses: ./.github/workflows/jira_notify.yml
    with:
      title: ${{ github.event.issue.title }}
      body: ${{ github.event.issue.body }}
      html_url: ${{ github.event.issue.html_url }}
      repo: ${{ github.event.repository.full_name }}
    secrets:
      AST_JIRA_API_TOKEN: ${{ secrets.AST_JIRA_API_TOKEN }}
      AST_JIRA_USER_EMAIL: ${{ secrets.AST_JIRA_USER_EMAIL }}
      JIRA_FIELDS_BUG: ${{ secrets.JIRA_FIELDS_BUG }}
      JIRA_FIELDS_OTHER: ${{ secrets.JIRA_FIELDS_OTHER }}